# fly.toml app configuration file generated for mat-iii-engine on 2026-06-09T22:11:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mat-iii-engine'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[env]
  III_QUEUE_ENABLED = 'true'
  III_STREAM_ENABLED = 'true'

[http_service]
  internal_port = 3111
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
